# Linear Algebra
- Vector Operations

In [2]:
import numpy as np

## Vector Operations

In [3]:
u = np.array([2, 4, 5, 6])

In [4]:
u

array([2, 4, 5, 6])

In [5]:
v = np.array([1, 0, 0, 2])

In [6]:
v

array([1, 0, 0, 2])

In [7]:
u + v

array([3, 4, 5, 8])

In [8]:
2 * u

array([ 4,  8, 10, 12])

### Multiplication
- Vector by Vector (dot product)
u · v = u₁v₁ + u₂v₂ + u₃v₃ + … + uₙvₙ
- Matrix by Vector
- Matrix by Matrix

In [13]:
u.shape[0]

4

In [14]:
v.shape[0]

4

In [21]:
u

array([2, 4, 5, 6])

In [22]:
v

array([1, 0, 0, 2])

In [23]:
def vector_vector_multi(u, v):
    assert u.shape[0] == v.shape[0] # to perform vector multiplication must have the same size

    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [24]:
vector_vector_multi(u, v)

np.float64(14.0)

In [25]:
u.dot(v)

np.int64(14)