# Introduction to NumPy
- Creating Arrays
- Multi-Dimensional Arrays
- Randomly Generated Arrays
- Element-Wise Operations
  - Comparison Operations
  - Logical Operations
- Summarizing Operations

In [1]:
import numpy as np

## Creating Arrays

In [2]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [9]:
arr[2] = 10

In [10]:
arr

array([ 1,  2, 10,  4,  5,  6])

## Multi-Dimensional Arrays

In [12]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [14]:
n[1] # Accessing Rows

array([4, 5, 6])

In [15]:
n[1, 1] # Accessing Row, Column

np.int64(5)

In [17]:
n[:, 1] # Accessing all rows in column 1

array([2, 5, 8])

## Randomly Generated Arrays

In [20]:
np.random.seed(2) # fix the random seed
np.random.rand(5, 2) # rows, columns

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [21]:
np.random.seed(2) # fix the random seed
np.random.randn(5, 2) # normal distribution

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [22]:
np.random.seed(2) # fix the random seed
np.random.randint(low=0, high=100, size=(5, 2)) # random integers b/w 0 & 100 

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-Wise Operations

In [23]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [24]:
a + 1

array([1, 2, 3, 4, 5])

In [25]:
a * 2

array([0, 2, 4, 6, 8])

In [26]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [29]:
b = (10 + (a * 2)) ** 2

In [31]:
b

array([100, 144, 196, 256, 324])

In [32]:
a + b # a - b, a * b, etc

array([100, 145, 198, 259, 328])

### Comparison Operations

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:
a >= 2

array([False, False,  True,  True,  True])

In [36]:
b

array([100, 144, 196, 256, 324])

In [37]:
a >= b

array([False, False, False, False, False])

In [38]:
a[a < b]

array([0, 1, 2, 3, 4])

## Summarizing Operations

In [39]:
a

array([0, 1, 2, 3, 4])

In [40]:
a.min()

np.int64(0)

In [41]:
a.max()

np.int64(4)

In [42]:
a.sum()

np.int64(10)

In [43]:
a.mean()

np.float64(2.0)

In [44]:
a.std()

np.float64(1.4142135623730951)

In [45]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
n.sum()

np.int64(45)